language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - client/node_modules
install:
  - cd client && yarn install --ignore-engines
script:
  - cd client && yarn test
  - cd client && yarn build
on:
  branch: master
