const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
  SYNC_COLLECTIONS_WITH_FIRESTORE: 'SYNC_COLLECTIONS_WITH_FIRESTORE'
};

export default ShopActionTypes;
